name: CI Release Helm Chart

on:
  release:
    types: [published]

env:
  REPO_NAME: magda-cloud-sql-proxy
  #S3 bucket name: this s3 bucket will be used to store published helm chart and index
  S3_BUCKET: magda-charts

jobs:
  release-helm-chart:
    name: Release Helm Chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: yarn install

      - name: helm-build-dependencies
        run: helm dep up deploy/${REPO_NAME}

      - name: helm-check
        run: yarn helm-lint

      - name: helm-chart-version-check
        run: node ./helm-chart-version-check.js deploy/${REPO_NAME}/Chart.yaml

      - name: Release Helm Chart
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd deploy
          mkdir -p sync_dir
          mkdir -p index_dir
          if ! aws s3 cp s3://${S3_BUCKET}/index.yaml index_dir/index.yaml; then echo "failed to copy current repo index" && exit 1; fi
          helm package -d sync_dir ${REPO_NAME}
          helm repo index --merge "index_dir/index.yaml" sync_dir
          mv -f sync_dir/index.yaml index_dir/index.yaml
          aws s3 sync sync_dir s3://${S3_BUCKET}/
          aws s3 cp index_dir/index.yaml s3://${S3_BUCKET}/index.yaml